org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=false
org.gradle.vfs.watch=false

org.gradle.internal.repository.max.retries=3

systemProp.java.net.preferIPv4Stack=true

minecraft_version=1.21.1
neo_version=21.1.172

mod_id=pmweather_tfc
mod_version=1.0.0-1.21.1-neoforge
mod_group_id=com.green_skeleton.pmweather_tfc
